# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Component-Server-Time
version:      1.02
version_from: lib/POE/Component/Server/Time.pm
installdirs:  site
requires:
    Carp:                          0
    POE:                           0.0607
    POE::Component::Server::Echo:  1.3
    Socket:                        0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
