---
abstract: 'A POE component that implements an RFC 868 Time server.'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.89'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-Server-Time
no_index:
  directory:
    - examples
    - inc
    - t
provides:
  POE::Component::Server::Time:
    file: lib/POE/Component/Server/Time.pm
    version: 1.14
requires:
  POE: 0.38
  POE::Component::Server::Echo: 1.58
  perl: 5.6.0
resources:
  homepage: http://github.com/bingos/poe-component-server-time/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bingos/poe-component-server-time.git
version: 1.14
